import Background from "./components/Background";
import Sidebar from "./components/Sidebar";
import { jsPDF } from "jspdf";
import StatCard from "./components/StatCard";
import RiskGauge from "./components/RiskGuage";
import Analytics from "./components/Analytics";
import { useState } from "react";
import axios from "axios";
import "./App.css";

function App() {
  const [prompt, setPrompt] = useState("");
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [history, setHistory] = useState([]);

  const scanPrompt = async () => {
    try {
      setLoading(true);

      const response = await axios.post("http://localhost:5000/scan", {
        prompt,
      });

      setResult(response.data);
      setHistory((prev) => [
  {
    prompt,
    risk: response.data.local?.risk || 0,
    blocked: response.data.local?.blocked,
    time: new Date().toLocaleTimeString(),
  },
  ...prev,
]);
    } catch (error) {
      console.error(error);
      alert("Unable to connect to backend.");
    } finally {
      setLoading(false);
    }
  };

  const local = result?.local || {};
  const security = result?.security || {};

  const getThreatLevel = () => {
    const risk = local.risk || 0;

    if (risk >= 70) return "🔴 HIGH";
    if (risk >= 30) return "🟠 MEDIUM";
    return "🟢 LOW";
  };

  const downloadReport = () => {
  const doc = new jsPDF();

  const threat = getThreatLevel();
  const decision = local.blocked ? "BLOCKED" : "SAFE";

  let y = 20;

  doc.setFontSize(22);
  doc.text("SecureGPT Security Report", 20, y);

  y += 12;
  doc.setFontSize(11);
  doc.text(
    `Generated: ${new Date().toLocaleString()}`,
    20,
    y
  );

  y += 15;

  doc.setFontSize(16);
  doc.text("Original Prompt", 20, y);

  y += 8;

  const original = doc.splitTextToSize(prompt, 170);
  doc.setFontSize(11);
  doc.text(original, 20, y);

  y += original.length * 6 + 10;

  doc.setFontSize(16);
  doc.text("Sanitized Prompt", 20, y);

  y += 8;

  const sanitized = doc.splitTextToSize(
    local.sanitizedText || "",
    170
  );

  doc.setFontSize(11);
  doc.text(sanitized, 20, y);

  y += sanitized.length * 6 + 10;

  doc.setFontSize(16);
  doc.text("Security Summary", 20, y);

  y += 10;

  doc.setFontSize(11);

  doc.text(`Risk Score : ${local.risk}/100`, 20, y);
  y += 7;

  doc.text(`Trust Score : ${local.trustScore}/100`, 20, y);
  y += 7;

  doc.text(`Threat Level : ${threat}`, 20, y);
  y += 7;

  doc.text(`Decision : ${decision}`, 20, y);
  y += 12;

  doc.setFontSize(16);
  doc.text("Findings", 20, y);

  y += 8;

  doc.setFontSize(11);

  if ((local.findings || []).length === 0) {
    doc.text("No sensitive information detected.", 20, y);
  } else {
    local.findings.forEach((item) => {
      doc.text("• " + item, 20, y);
      y += 7;
    });
  }

  y += 12;

  doc.setFontSize(10);
  doc.text(
    "Generated by SecureGPT - AI Prompt Security Scanner",
    20,
    y
  );

  doc.save("SecureGPT_Report.pdf");
};

  return (

    <div className="layout">

    <Sidebar />
    <div className="app">

      <Background />

      <div className="secure-container">

        <div className="hero">

          <h1 className="title">
            🔒 SecureGPT
          </h1>

          <p className="subtitle">
            AI Prompt Security Scanner
          </p>

          <p className="tagline">
            Detect • Sanitize • Protect
          </p>

        </div>

        <div id="scanner" className="card input-card">

          <h2>Enter Prompt</h2>

          <textarea
            rows="8"
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="Type your AI prompt here..."
            className="prompt-box"
          />

          <div className="button-container">

            <button
              className="btn"
              onClick={scanPrompt}
              disabled={loading}
            >
              {loading ? "Scanning..." : "🚀 Scan Prompt"}
            </button>

          </div>

        </div>

        {loading && (
          <div className="loading-card">
            <div className="spinner"></div>
            <p>Analyzing Prompt...</p>
          </div>
        )}

      
        {result && (
          <>
          <div
  id="dashboard"
  style={{
    display: "grid",
    gridTemplateColumns: "repeat(4,1fr)",
    gap: "20px",
    marginBottom: "25px"
  }}
>
  <StatCard
    title="Risk"
    value={local.risk || 0}
    color="#ef4444"
  />

  <StatCard
    title="Trust"
    value={local.trustScore || 0}
    color="#22c55e"
  />

  <StatCard
    title="Findings"
    value={(local.findings || []).length}
    color="#f59e0b"
  />

  <StatCard
    title="Decision"
    value={local.blocked ? "BLOCK" : "SAFE"}
    color={local.blocked ? "#ef4444" : "#22c55e"}
  />
</div>

            {local.blocked && (
              <div className="alert">
                ⚠ HIGH RISK PROMPT DETECTED
              </div>
            )}

            <div className="grid">

              {/* Risk Dashboard */}

              <div className="card">

                <h2>🛡 Risk Dashboard</h2>

                <div className="metric">

                  <span>Risk Score</span>

                  <strong>{local.risk || 0}/100</strong>

                </div>

                <div className="metric">

                  <span>Trust Score</span>

                  <strong>{local.trustScore || 0}/100</strong>

                </div>

                <RiskGauge score={local.trustScore || 0} />

                <div className="status-row">

                  <span>Threat Level</span>

                  <strong>{getThreatLevel()}</strong>

                </div>

                <div className="status-row">

                  <span>Status</span>

                  <strong>
                    {local.blocked
                      ? "❌ BLOCKED"
                      : "✅ ALLOWED"}
                  </strong>

                </div>

              </div>

              {/* System Status */}

              <div className="card">

                <h2>⚡ Security Engine</h2>

                <div className="metric">

                  <span>Final Decision</span>

                  <strong>
                    {security.status === "BLOCKED"
                      ? "❌ BLOCKED"
                      : "✅ SAFE"}
                  </strong>

                </div>

                <div className="metric">

                  <span>Risk Score</span>

                  <strong>{security.riskScore || 0}</strong>

                </div>

                <div className="metric">

                  <span>ArmorIQ</span>

                  <strong>
                    {result.armoriq
                      ? "🟢 Connected"
                      : "⚪ Offline"}
                  </strong>

                </div>

                <div className="metric">

                  <span>Audit Log</span>

                  <strong>✔ Created</strong>

                </div>

              </div>

            </div>
                        {/* Findings */}

            <div className="card section-card">

              <h2>🔍 Findings</h2>

              {(local.findings || []).length === 0 ? (

                <div className="safe">
                  ✅ No sensitive information detected.
                </div>

              ) : (

                <div className="findings-list">

                  {local.findings.map((item, index) => (

                    <div key={index} className="finding-item">

                      <span>⚠</span>

                      <span>{item}</span>

                    </div>

                  ))}

                </div>

              )}

            </div>

            {/* Sanitized Prompt */}

            <div  id="reports" className="card section-card">

  <h2>🧹 Prompt Comparison</h2>

  <div
    style={{
      display: "grid",
      gridTemplateColumns: "1fr 1fr",
      gap: "20px",
      marginTop: "20px",
    }}
  >

    {/* Original */}

    <div>

      <h3 style={{ marginBottom: "10px" }}>
        Original Prompt
      </h3>

      <textarea
        readOnly
        value={prompt}
        className="output-box"
      />

    </div>

    {/* Sanitized */}

    <div>

      <h3 style={{ marginBottom: "10px" }}>
        Sanitized Prompt
      </h3>

      <textarea
        readOnly
        value={local.sanitizedText || ""}
        className="output-box"
      />

    </div>

  </div>

  <div
  className="button-container"
  style={{
    display: "flex",
    gap: "15px",
    justifyContent: "center",
    marginTop: "20px",
  }}
>

  <button
    className="btn success-btn"
    onClick={async () => {
    const text = local.sanitizedText || "";

    try {
      await navigator.clipboard.writeText(text);
      alert("✅ Copied!");
    } catch (err) {
      const textarea = document.createElement("textarea");
      textarea.value = text;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);

      alert("✅ Copied!");
    }
  }}
  >
    📋 Copy Sanitized Prompt
  </button>

  <button
    className="btn"
    onClick={downloadReport}
    style={{
      background: "#9333ea",
    }}
  >
    📄 Download PDF Report
  </button>

</div>

</div>

</>
)}

<div id="history"  className="card section-card">

  <h2>🕒 Recent Scans</h2>

  {history.length === 0 ? (

    <p>No scans yet.</p>

  ) : (

    history.map((item, index) => (

      <div
        key={index}
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          padding: "12px",
          marginTop: "10px",
          borderBottom: "1px solid #334155",
        }}
      >

        <div>

          <strong>
            {item.blocked ? "🔴" : "🟢"}
          </strong>

          {" "}

          {item.prompt.length > 50
            ? item.prompt.substring(0, 50) + "..."
            : item.prompt}

        </div>

        <div>

          Risk: {item.risk}

          <br />

          <small>{item.time}</small>

        </div>

      </div>

    ))

  )}

</div>

<div id="analytics">
  <Analytics history={history} />
</div>

        {/* Footer */}

        <footer className="footer">

          <p>
            🔒 SecureGPT • AI Prompt Security Scanner
          </p>

          <p>
            Built with React + Express + Local Scanner + ArmorIQ
          </p>

        </footer>

      </div>

    </div>

  </div>  
);

 
}

export default App;

